apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    basicAuth: false
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{service_name="${__span.tags["service.name"]}"} |= `${__span.tags["payment.uetr"]}`'
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - key: service.name
            value: service
        queries:
          - name: Request Rate
            query: rate(payment_payment_requests_total{service="$${__tags.service}"}[5m])
          - name: P99 Latency
            query: histogram_quantile(0.99, rate(payment_payment_duration_ms_bucket{service="$${__tags.service}"}[5m]))
      serviceMap:
        datasourceUid: prometheus
      search:
        hide: false
      nodeGraph:
        enabled: true

  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: false
    jsonData:
      timeInterval: "15s"

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    jsonData:
      derivedFields:
        - name: traceId
          matcherRegex: 'trace_id=([a-f0-9]{32})'
          url: "$${__value.raw}"
          datasourceUid: tempo
          urlDisplayLabel: View Trace
